# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               michael wolfendale
tagline:             'wolfendale.github.io'
description:         ''
url:                 http://wolfendale.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Michael Wolfendale
  url:               https://github.com/wolfendale
  email:             michael.wolfendale@gmail.com

# Custom vars
version:             1.0.0
