permalink:           pretty

# Setup
title:               michael wolfendale
url:                 http://wolfendale.github.io

# About/contact
author:
  name:              Michael Wolfendale
  url:               https://github.com/wolfendale
  email:             michael.wolfendale@gmail.com

# Custom vars
version:             1.0.0

plugins:
  - "jekyll-autoprefixer"

sass:
  sass_dir: "assets/css"

defaults:
  - 
    scope:
      type: "posts"
    values:
      layout: "post"
      author: "Michael Wolfendale"